In [1]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [6]:
df=pd.read_csv('covid_toy.csv')

In [7]:
df.shape


(100, 6)

In [10]:
df.sample(4)

age  gender  fever   cough       city has_covid
47   18  Female  104.0    Mild  Bangalore        No
91   38    Male    NaN    Mild      Delhi       Yes
5    84  Female    NaN    Mild  Bangalore       Yes
94   79    Male    NaN  Strong    Kolkata       Yes

In [11]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [13]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [14]:
#  cough is ordinal categorical and city and gender are nominal categorical

In [15]:
#  age is perfect for now than fever has some missing values

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [18]:
x_train

age  gender  fever   cough       city
41   82    Male    NaN    Mild    Kolkata
28   16    Male  104.0    Mild    Kolkata
13   64    Male  102.0    Mild  Bangalore
15   70    Male  103.0  Strong    Kolkata
47   18  Female  104.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
45   72    Male   99.0    Mild  Bangalore
37   55    Male  100.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
32   34  Female  101.0  Strong      Delhi
19   42  Female    NaN  Strong  Bangalore

[80 rows x 5 columns]

# doing mannually

In [19]:
# applying simple imputer to fever column
si=SimpleImputer() # replaced by mean of data
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.fit_transform(x_test[['fever']])
x_train_fever


array([[100.80555556],
       [104.        ],
       [102.        ],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [100.80555556],
       [102.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [102.        ],
       [103.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [100.80555556],
       [104.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [102.        ],
       [103.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [100

In [21]:
# ordinal encoding cough

oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

x_test_cough=oe.fit_transform(x_test[['cough']])
x_train_cough

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],

In [22]:
#   Ohe on gender and city columns
ohe=OneHotEncoder(drop='first',sparse_output=False)

x_train_g_c=ohe.fit_transform(x_train[['gender','city']])
x_test_g_c=ohe.fit_transform(x_test[['gender','city']])



In [23]:
x_train_g_c

array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],


In [24]:
x_train

age  gender  fever   cough       city
41   82    Male    NaN    Mild    Kolkata
28   16    Male  104.0    Mild    Kolkata
13   64    Male  102.0    Mild  Bangalore
15   70    Male  103.0  Strong    Kolkata
47   18  Female  104.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
45   72    Male   99.0    Mild  Bangalore
37   55    Male  100.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
32   34  Female  101.0  Strong      Delhi
19   42  Female    NaN  Strong  Bangalore

[80 rows x 5 columns]

In [29]:
#  extracting age

x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values
x_train_age


array([[82],
       [16],
       [64],
       [70],
       [18],
       [69],
       [71],
       [80],
       [25],
       [24],
       [27],
       [34],
       [22],
       [34],
       [69],
       [82],
       [20],
       [19],
       [81],
       [82],
       [60],
       [10],
       [14],
       [73],
       [38],
       [34],
       [12],
       [11],
       [20],
       [33],
       [50],
       [64],
       [48],
       [44],
       [49],
       [56],
       [83],
       [ 5],
       [26],
       [10],
       [65],
       [83],
       [42],
       [ 5],
       [65],
       [16],
       [51],
       [75],
       [25],
       [47],
       [66],
       [27],
       [14],
       [31],
       [80],
       [54],
       [19],
       [71],
       [27],
       [38],
       [83],
       [46],
       [13],
       [75],
       [84],
       [65],
       [59],
       [68],
       [79],
       [42],
       [60],
       [81],
       [47],
       [65],
       [51],
       [72],
       [55],

In [30]:
x_train_age.shape

(80, 1)

In [27]:
 # combining all the columns

In [34]:
train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_cough,x_train_g_c),axis=1)
test_transformed=np.concatenate((x_test_age,x_test_fever,x_test_cough,x_test_g_c),axis=1)
train_transformed.shape

(80, 7)

#With Sklear class

In [35]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
     ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [37]:
transformer.fit_transform(x_train)

array([[100.80555556,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  70.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.    

In [38]:
transformer.transform(x_test)

array([[100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  11.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [100.80555556,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  24.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  15.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.    

In [44]:
data=pd.DataFrame(transformer.fit_transform(x_train))

In [45]:
data


0    1    2    3    4    5     6
0   100.805556  0.0  1.0  0.0  1.0  0.0  82.0
1   104.000000  0.0  1.0  0.0  1.0  0.0  16.0
2   102.000000  0.0  1.0  0.0  0.0  0.0  64.0
3   103.000000  1.0  1.0  0.0  1.0  0.0  70.0
4   104.000000  0.0  0.0  0.0  0.0  0.0  18.0
..         ...  ...  ...  ...  ...  ...   ...
75   99.000000  0.0  1.0  0.0  0.0  0.0  72.0
76  100.000000  0.0  1.0  0.0  1.0  0.0  55.0
77  100.000000  1.0  0.0  0.0  0.0  0.0  19.0
78  101.000000  1.0  0.0  1.0  0.0  0.0  34.0
79  100.805556  1.0  0.0  0.0  0.0  0.0  42.0

[80 rows x 7 columns]

In [46]:
data.columns=['fever','cough','gender_m','gender_f','city_a','city_b','age']

In [47]:
data

fever  cough  gender_m  gender_f  city_a  city_b   age
0   100.805556    0.0       1.0       0.0     1.0     0.0  82.0
1   104.000000    0.0       1.0       0.0     1.0     0.0  16.0
2   102.000000    0.0       1.0       0.0     0.0     0.0  64.0
3   103.000000    1.0       1.0       0.0     1.0     0.0  70.0
4   104.000000    0.0       0.0       0.0     0.0     0.0  18.0
..         ...    ...       ...       ...     ...     ...   ...
75   99.000000    0.0       1.0       0.0     0.0     0.0  72.0
76  100.000000    0.0       1.0       0.0     1.0     0.0  55.0
77  100.000000    1.0       0.0       0.0     0.0     0.0  19.0
78  101.000000    1.0       0.0       1.0     0.0     0.0  34.0
79  100.805556    1.0       0.0       0.0     0.0     0.0  42.0

[80 rows x 7 columns]